<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>Editor</RootNamespace>
    <Platforms>x64;x86</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <NoWarn>1701;1702;IL2121;CS8601;IL2121;CS8625</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <NoWarn>1701;1702;IL2121;CS8601;IL2121;CS8625</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="runtimes\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bufdio" Version="0.1.0" />
    <PackageReference Include="DirectXTexNet" Version="1.0.7" />
    <PackageReference Include="GdkSharp" Version="3.24.24.95" />
    <PackageReference Include="GioSharp" Version="3.24.24.95" />
    <PackageReference Include="Hexa.NET.GLFW" Version="1.0.5" />
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.ImGui.Backends.GLFW" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.ImGui.Widgets" Version="1.2.15" />
    <PackageReference Include="Hexa.NET.OpenGL.ARB" Version="1.1.0" />
    <PackageReference Include="Hexa.NET.OpenGL.Core" Version="1.1.0" />
    <PackageReference Include="Hexa.NET.OpenGL4" Version="1.1.0" />
    <PackageReference Include="Microsoft.Direct3D.DXC" Version="1.9.2602.17" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.1" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.264">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NLua" Version="1.7.8" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.1" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.1" />
    <PackageReference Include="Vortice.Dxc" Version="3.8.2" />
    <PackageReference Include="Vortice.SpirvCross" Version="1.5.4" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="runtimes\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="runtimes\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BlurFileFormats\BlurFileFormats.csproj" />
    <ProjectReference Include="..\..\HlslDecompiler\HlslDecompiler.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="libs\HLSLcc\hlslcc.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="libs\PortAudio\Windows\libportaudio.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Fonts\Roboto-Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Fonts\Roboto-Light.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Fonts\Roboto-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Shaders\skybox.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Shaders\skybox.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="libs\PortAudio\Windows\" />
  </ItemGroup>
</Project>